# Generated by Django 4.2.7 on 2025-09-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_profile_email_alter_comment_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
